### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ycc123abc** [ly-rgb/env-js#2]
我在尝试用志远的框架过掉抖音的a_bogus,发现了你的代码里的Performance，因为正好抖音也要补这个玩意，所以直接把你的这个文件拿了过来，于是报了一个这个错误：
ReferenceError: Cannot access 'Performance' before initialization
at c:\Users\12241\Desktop\catvm2\env-js-main\debugger.js:135:13
at Script.runInContext (c:\Users\12241\Desktop\catvm2\env-js-main\lib\vm.js:148:12)
at VM.runScript (c:\Users\12241\Desktop\catvm2\env-js-main\node_modules\vm2\lib\vm.js:288:18)
at VM.run (c:\Users\12241\Desktop\catvm2\env-js-main\node_modules\vm2\lib\vm.js:509:16)
at Object. (c:\Users\12241\Desktop\catvm2\env-js-main\index.js:13:4)
at Module._compile (c:\Users\12241\Desktop\catvm2\env-js-main\lib\internal\modules\cjs\loader.js:1358:14)
at Module._extensions..js (c:\Users\12241\Desktop\catvm2\env-js-main\lib\internal\modules\cjs\loader.js:1416:10)
at Module.load (c:\Users\12241\Desktop\catvm2\env-js-main\lib\internal\modules\cjs\loader.js:1208:32)
at Module._load (c:\Users\12241\Desktop\catvm2\env-js-main\lib\internal\modules\cjs\loader.js:1024:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {stack: "ReferenceError: Cannot access 'Performance' b…Main] (node:internal/modules/run_main:174:12)", message: "Cannot access 'Performance' before initialization"}

把整个项目拿过来。依然报了这个错误

**Comment by ly-rgb** [comment]
catvm2.node.js中 Performance文件的加载顺序应该优于DOM加载，已经更改，谢谢提醒
